@url=https://firestore.googleapis.com/v1/projects/zomujo-emr/databases/(default)/documents:runQuery?key=AIzaSyDhsg8Ws-Ut0ieDtVnWtnGXs15AU2Oiw8Y


POST {{url}}
Content-Type: application/json

{
	"structuredQuery": {
    "from": [{ "collectionId": "posts" }],
	  "limit": 1,
		"select": {
			"fields": [
			{ "fieldPath": "title"}
			]
		}
} }
